default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Rlxrvt1241x@
  host: "127.0.0.1"
  port: 3306

development:
  <<: *default
  database: db_noticia

test:
  <<: *default
  database: db_noticia

production:
  <<: *default
  database: db_noticia
